### ISSUE TITLE
frame update bug

### ISSUE THREAD

**Issue by AppLoidx** [EgorovM/cpp_snake#1]
Тут какой-то баг при работе с ncurses и при обновлении кадра возникает старый вывод консоли

![lB0Sp4hVL7](https://user-images.githubusercontent.com/32590754/105803116-d4da7680-5fad-11eb-8d0d-3b7c9a435004.gif)

И проблема вряд ли в самой консоли так как, например, ncurses в другой программе работает нормально

![H6csvJczzr](https://user-images.githubusercontent.com/32590754/105803307-3995d100-5fae-11eb-9468-3c03dcffd2ef.gif)

Правда, я там компилил уже через gcc для си

**Comment by EgorovM** [comment]
Thanks, Fixed!
